* 信用风险管理
[[https://www.jianshu.com/p/9cf641f5eeef][信用风险管理篇]]
** 信用风险度量
参考：《我国商业银行信用风险度量和管理研究》，2011年，刘迎春。

现代意义下的信用风险度量内容包括：
- 单笔贷款信用风险度量
- 信贷组合信用风险度量
- 银行经济资本度量
- 经风险调整的资本收益率度量
这四个模块，及对各个模块中所涉及的多个参数,包括：
- 单笔贷款的违约率
- 违约风险敞口
- 违约损失率
- 信贷组合违约相关系数
- 经济资本
- 经风险调整的资本收益率值的估计
在现代信用风险度量技术中,相对而言,只有违约率度量的技术相对成熟,其他的仍在在探索阶段。
** 商业银行信用风险管理的内容
参考：《我国商业银行信用风险度量和管理研究》，2011年，刘迎春。

信用风险管理包括信用风 险的定价管理,信用风险的贷款组合优化管理,信用风险的资本管理及信
用风险的转 移和分解管理等。商业银行信用风险的定价管理包括银行依据信用风险计量结果,
确定是否对某个客户提供信贷服务、采用何种信贷利率、给予多大的信贷额度以及具体的信贷条款有
哪些等内容。

商业银行信用风险管理体系，包括
- 信用风险识别
- 信用风险度量
- 信用风险预警

信用风险量化管理经历了一个从初级到高级，从简单到复杂的过程。在90年代以前，
主要利用信用评分方法对企业进行违约分析，如果企业存在较高的违约可能，
那么银行将拒绝与其合作，利用风险规避的手段进行信用风险管理。进入90年代以后，
随着信息技术的发展，信贷组合损失开始成为国际大型商业银行和金融中介服务机构
研究的重点，并先后推出现代信用风险度量模型，如J.P.摩根的Credit Metrics
模型（1997）、KMV （1993）的EDF模型、CSFP的Credit Risk+ 模型（1997）、
麦肯锡的CPV模型（1998）等，使得商业银行信用风险管理从传统的信用风险识别和违约评估，
过渡到现代信用风险量 化模型阶段。它们所提供的这些的思想和方法，
在国外银行中被广泛应用于信用风险量化与管理，巴塞尔委员会公布《新资本协议》中所推出的内
部评级法（IRB），也是基于上述模型的适用性考虑后的折中产物。

资本包括三种类型：会计资本5、经济资本和监管资本，

银行面临的信用风险：
- 证券投资信用风险
- 信贷风险
- 银行自身的信用风险

银行信贷风险包括：
- 信用违约风险default risk
- 信用息差风险spread risk
** 信用风险的研究现状
国外学者关于信用风险度量的研究始于 20 世纪 60 年代，总体来看，可以划分为五个阶段，
即多元判别分析阶段、多元非线性回归分析阶段、人工智能阶段、组合信用风 险度量模型阶段以及
信用风险内部度量阶段。
** 经济资本
** 预期损失EL
** 非预期损失UL
[[http://www.doc88.com/p-180631721954.html][非预期损失的推导]]
